# Generated by Django 4.1.1 on 2022-09-23 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='номер счета')),
                ('bank_name', models.CharField(default='Star-Bank', max_length=128, verbose_name='банк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'счет',
                'verbose_name_plural': 'счета',
            },
        ),
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('author', models.CharField(blank=True, max_length=128, null=True, verbose_name='автор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('example', models.CharField(blank=True, max_length=128, null=True, verbose_name='пример')),
            ],
            options={
                'verbose_name': 'дизайн карт',
                'verbose_name_plural': 'дизайны карт',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип транзакции',
                'verbose_name_plural': 'тип транзакций',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='сумма')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=64, verbose_name='валюта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('from_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_from', to='bank.bankaccount', verbose_name='от счета')),
                ('to_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_to', to='bank.bankaccount', verbose_name='к счета')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.transactiontype', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=64, verbose_name='валюта')),
                ('money', models.FloatField(default=0.0, verbose_name='сумма')),
                ('interest_rate', models.FloatField(default=0.0, verbose_name='ставка %')),
                ('min_value', models.PositiveIntegerField(default=0, verbose_name='минимальная сумма')),
                ('max_value', models.PositiveIntegerField(default=100000, verbose_name='максимальная сумма')),
                ('date_issue', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('completion_date', models.DateField(auto_now_add=True, verbose_name='дата истечения')),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount', verbose_name='счет')),
            ],
            options={
                'verbose_name': 'вклад',
                'verbose_name_plural': 'вклады',
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='процент')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.transactiontype', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'кэшбэк',
                'verbose_name_plural': 'кэшбэки',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('push_price', models.PositiveIntegerField(default=30, verbose_name='цена уведомлений')),
                ('service_price', models.PositiveIntegerField(default=50, verbose_name='цена обсуживания')),
                ('cashbacks', models.ManyToManyField(to='bank.cashback', verbose_name='кэшбэк')),
            ],
            options={
                'verbose_name': 'тип карт',
                'verbose_name_plural': 'типы карт',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=64, verbose_name='валюта')),
                ('money', models.FloatField(default=0.0, verbose_name='сумма')),
                ('is_push', models.BooleanField(default=False, verbose_name='уведомления')),
                ('date_issue', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('completion_date', models.DateField(auto_now_add=True, verbose_name='дата истечения')),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount', verbose_name='счет')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.cardtype', verbose_name='тип карты')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.carddesign', verbose_name='дизайн')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
            },
        ),
    ]
