# Generated by Django 4.1.1 on 2022-09-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankaccount_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashback',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='cashback',
            name='transaction_type',
            field=models.ManyToManyField(to='bank.transactiontype', verbose_name='типы транзакций'),
        ),
    ]
