# Generated by Django 4.1.1 on 2022-09-27 08:58

import bank.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_cashback_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name': 'тип транзакции', 'verbose_name_plural': 'типы транзакций'},
        ),
        migrations.AlterField(
            model_name='card',
            name='completion_date',
            field=models.DateField(default=bank.models.get_completion_data, verbose_name='дата истечения'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_issue',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
    ]
