# Generated by Django 4.1.1 on 2022-09-27 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_transactiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_issue',
            field=models.DateField(default=datetime.date.today, verbose_name='дата создания'),
        ),
    ]
