# Generated by Django 4.1.1 on 2022-09-29 08:52

import bank.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_card_date_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='completion_date',
            field=models.DateField(default=bank.models.get_completion_data, verbose_name='дата истечения'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date_issue',
            field=models.DateField(default=datetime.date.today, verbose_name='дата создания'),
        ),
    ]
