# Generated by Django 4.1.1 on 2022-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_deposit_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='cashback_money',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма кэшбэка'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashback_money',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма кэшбэка'),
        ),
    ]
