# Generated by Django 4.1.1 on 2022-09-16 11:12

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('monthly_price', models.PositiveIntegerField(default=0, verbose_name='Месячная плата')),
                ('transfer_limit', models.PositiveIntegerField(default=50000, help_text='Сумма лимита перевода в месяц', verbose_name='Лимит перевода')),
                ('free_card_maintenance', models.BooleanField(default=False, verbose_name='Бесплатное обслуживание карт')),
                ('additional_interest_rate', models.FloatField(default=0.0, verbose_name='Доплнительная процентная ставка')),
            ],
            options={
                'verbose_name': 'Тариф Аккаунта',
                'verbose_name_plural': 'Тарифы Аккаунта',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('fio', models.CharField(blank=True, max_length=128, verbose_name='ФИО')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='Страна')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.accounttarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
